on: 
  workflow_dispatch:

name: Deploy application to azure
env:
#   RESOURCE_GROUP_NAME: "sample-ganes-rg"
#   RESOURCE_GROUP_LOCATION: "eastus"
#   AKS_CLUSTER_NAME: "sample-ganes-cluster"
  RESOURCE_GROUP_NAME: ${{acc.RESOURCE_GROUP}}
  RESOURCE_GROUP_LOCATION: ${{acc.RESOURCE_GROUP_LOCATION}}
  AKS_CLUSTER_NAME: "sample-ganes-cluster"

jobs:
  provision-azure-resources:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name: Deploy application to function app
      uses: Azure/functions-action@v1.3.1
      with:
        app-name: 'sample-node-app'
